# Generated by Django 6.1 on 2026-08-20 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academica', '0002_initial'),
        ('asistencia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='justificacion',
            name='alumno',
            field=models.ForeignKey(limit_choices_to={'rol': 'alumno'}, on_delete=django.db.models.deletion.CASCADE, related_name='justificaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='justificacion',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificaciones', to='academica.curso'),
        ),
        migrations.AddField(
            model_name='justificacion',
            name='respondido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificaciones_respondidas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='alumno',
            field=models.ForeignKey(limit_choices_to={'rol': 'alumno'}, on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='academica.curso'),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='horario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias', to='academica.horario'),
        ),
        migrations.AddField(
            model_name='registroasistencia',
            name='registrado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sesionqr',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_qr', to='academica.curso'),
        ),
        migrations.AddField(
            model_name='sesionqr',
            name='docente',
            field=models.ForeignKey(limit_choices_to={'rol': 'docente'}, on_delete=django.db.models.deletion.CASCADE, related_name='sesiones_qr_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sesionqr',
            name='horario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sesiones_qr', to='academica.horario'),
        ),
        migrations.AlterUniqueTogether(
            name='registroasistencia',
            unique_together={('alumno', 'curso', 'fecha')},
        ),
    ]
