# Generated by Django 6.1 on 2026-08-20 04:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='asignaciondocente',
            name='docente',
            field=models.ForeignKey(limit_choices_to={'rol': 'docente'}, on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_docente', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ciclo',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ciclos', to='academica.carrera'),
        ),
        migrations.AddField(
            model_name='curso',
            name='ciclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cursos', to='academica.ciclo'),
        ),
        migrations.AddField(
            model_name='asignaciondocente',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones', to='academica.curso'),
        ),
        migrations.AddField(
            model_name='horario',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='academica.curso'),
        ),
        migrations.AddField(
            model_name='inscripcionalumno',
            name='alumno',
            field=models.ForeignKey(limit_choices_to={'rol': 'alumno'}, on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inscripcionalumno',
            name='ciclo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='academica.ciclo'),
        ),
        migrations.AddField(
            model_name='inscripcionalumno',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='academica.curso'),
        ),
        migrations.AddField(
            model_name='toleranciaconfig',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tolerancias', to='academica.curso'),
        ),
        migrations.AddField(
            model_name='toleranciaconfig',
            name='docente',
            field=models.ForeignKey(limit_choices_to={'rol': 'docente'}, on_delete=django.db.models.deletion.CASCADE, related_name='tolerancias_config', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='ciclo',
            unique_together={('carrera', 'numero', 'semestre', 'anio')},
        ),
        migrations.AlterUniqueTogether(
            name='asignaciondocente',
            unique_together={('docente', 'curso')},
        ),
        migrations.AlterUniqueTogether(
            name='horario',
            unique_together={('curso', 'dia', 'hora_inicio')},
        ),
        migrations.AlterUniqueTogether(
            name='inscripcionalumno',
            unique_together={('alumno', 'curso', 'ciclo')},
        ),
        migrations.AlterUniqueTogether(
            name='toleranciaconfig',
            unique_together={('curso', 'docente')},
        ),
    ]
