# Generated by Django 6.1 on 2026-08-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('editar', 'Editar'), ('eliminar', 'Eliminar'), ('consultar', 'Consultar'), ('login', 'Inicio de Sesion'), ('logout', 'Cierre de Sesion'), ('exportar', 'Exportar'), ('otro', 'Otro')], max_length=20)),
                ('modelo', models.CharField(max_length=100)),
                ('objeto_id', models.IntegerField(blank=True, null=True)),
                ('descripcion', models.TextField()),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Registro de Auditoria',
                'verbose_name_plural': 'Registros de Auditoria',
                'ordering': ['-created_at'],
            },
        ),
    ]
